const state = { channels: [], logs: [], selectedId: null, demo: true, days: 7 };
const $ = (s) => document.querySelector(s);
const fmt = (n, d = 0) => Number(n || 0).toLocaleString('zh-CN', { maximumFractionDigits: d });
const pct = (n, d = 1) => `${(Number(n || 0) * 100).toFixed(d)}%`;
const dateKey = (ts) => new Date(Number(ts || 0) * 1000).toISOString().slice(0, 10);
const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
$('#reportDate').value = yesterday;
$('#startDate').value = new Date(Date.now() - 7 * 86400000).toISOString().slice(0, 10);
$('#endDate').value = new Date().toISOString().slice(0, 10);
function daysAgo(n) { return Math.floor((Date.now() - n * 86400000) / 1000); }
function demoData() {
  const channels = [{ id: 355, name: '示例渠道 A', status: 1, response_time: 820, used_quota: 18420000, balance: 42680000, models: 'gpt-4o,gpt-4o-mini' }, { id: 417, name: 'Claude · 稳定备用', status: 1, response_time: 910, used_quota: 12840000, balance: 25100000, models: 'claude-3-5-sonnet,claude-3-haiku' }, { id: 288, name: 'DeepSeek · 性价比', status: 1, response_time: 740, used_quota: 9680000, balance: 18300000, models: 'deepseek-chat,deepseek-reasoner' }, { id: 502, name: 'Gemini · 长上下文', status: 1, response_time: 1380, used_quota: 7420000, balance: 8800000, models: 'gemini-1.5-pro' }, { id: 163, name: 'Azure · 低优先级', status: 0, response_time: 2140, used_quota: 3220000, balance: 4500000, models: 'gpt-4o' }];
  const models = ['gpt-4o-mini', 'gpt-4o', 'claude-3-5-sonnet', 'deepseek-chat', 'gemini-1.5-pro']; const logs = [];
  channels.forEach((c, ci) => { for (let d = 0; d < 14; d++) { const count = Math.max(5, 42 - ci * 5 - (d % 5) * 2 + ((ci + d) % 4) * 3); for (let i = 0; i < count; i++) { const fail = (ci === 4 && i % 4 === 0) || (ci === 3 && i % 17 === 0) || (ci === 2 && i % 19 === 0); const model = models[(i + ci) % models.length]; const use = Math.round((c.response_time * (0.8 + ((i * 17) % 50) / 100)) + (fail ? 1200 : 0)); logs.push({ id: `${c.id}-${d}-${i}`, channel: c.id, channel_name: c.name, created_at: daysAgo(d) - i * 190, type: fail ? 5 : 2, content: fail ? (i % 2 ? '上游超时，请稍后重试' : '429 rate limit exceeded') : '请求成功', model_name: model, quota: Math.round((90 + (i * 37) % 230) * (fail ? .8 : 1)), use_time: use, request_id: `req_${c.id}_${d}_${i}`, is_stream: i % 2 === 0 }); } } }); return { channels, logs };
}
function unwrapItems(input) { if (Array.isArray(input)) return input; return input?.data?.items || input?.items || []; }
function isError(log) { return Number(log.type) === 5 || /错误|失败|超时|rate.?limit|invalid|unauthor|error|timeout/i.test(String(log.content || '')); }
function analyze(channel, logs) {
  const items = logs.filter(l => Number(l.channel) === Number(channel.id)); const requests = items.length, errors = items.filter(isError).length, success = requests ? 1 - errors / requests : 0; const times = items.map(l => Number(l.use_time || l.response_time || 0)).filter(Boolean).sort((a, b) => a - b); const avgTime = times.length ? times.reduce((a, b) => a + b, 0) / times.length : Number(channel.response_time || 0); const p95 = times.length ? times[Math.min(times.length - 1, Math.floor(times.length * .95))] : avgTime; const quota = items.reduce((s, l) => s + Number(l.quota || 0), 0), perRequest = requests ? quota / requests : 0; const modelMap = {}; items.forEach(l => { const k = l.model_name || '未知模型'; modelMap[k] = (modelMap[k] || 0) + 1; }); const daily = {};
  items.forEach(l => { const k = dateKey(l.created_at || Date.now() / 1000); daily[k] = daily[k] || { requests: 0, errors: 0, quota: 0, times: [] }; daily[k].requests++; daily[k].quota += Number(l.quota || 0); daily[k].times.push(Number(l.use_time || 0)); if (isError(l)) daily[k].errors++; }); const vals = Object.values(daily), recent = vals.slice(-Math.min(3, vals.length)).reduce((s, v) => s + v.requests, 0), prior = vals.slice(0, Math.max(1, vals.length - 3)).reduce((s, v) => s + v.requests, 0); const trend = prior ? (recent / Math.max(1, Math.min(3, vals.length))) / (prior / Math.max(1, vals.length - 3)) - 1 : 0; const anomaly = items.filter(l => isError(l) || Number(l.use_time || 0) > Math.max(2500, p95) || Number(l.quota || 0) > perRequest * 2.4).sort((a, b) => Number(b.use_time || 0) - Number(a.use_time || 0)).slice(0, 10);
  const latencyScore = Math.max(0, Math.min(1, 1 - Math.max(0, avgTime - 450) / 1800)), costScore = Math.max(0, Math.min(1, 1 - Math.max(0, perRequest - 120) / 300)), coverageScore = Math.min(1, Object.keys(modelMap).length / 4), trendScore = Math.max(0, Math.min(1, .6 + trend * .5)); const score = Math.round(success * 35 + (1 - errors / Math.max(requests, 1)) * 20 + latencyScore * 15 + costScore * 15 + coverageScore * 8 + trendScore * 7); const verdict = score >= 85 ? '建议续费' : score >= 70 ? '谨慎续费' : score >= 55 ? '暂不续费' : '建议更换渠道', tone = score >= 85 ? 'good' : score >= 70 ? 'warn' : 'bad'; return { channel, items, requests, errors, success, avgTime, p95, quota, perRequest, modelMap, daily, trend, anomaly, score, verdict, tone };
}
function setData(data, demo = false) { state.channels = data.channels || []; state.logs = data.logs || []; state.demo = demo; state.selectedId = state.selectedId && state.channels.some(c => Number(c.id) === Number(state.selectedId)) ? state.selectedId : state.channels[0]?.id; populateChannelSelect(); renderAll(); $('#dataStatus').innerHTML = `${demo ? '当前使用演示数据' : '已连接 NewAPI'} · 已识别 <strong>${state.channels.length}</strong> 个渠道`; }
function selectedAnalysis() { const c = state.channels.find(c => Number(c.id) === Number(state.selectedId)) || state.channels[0]; return c ? analyze(c, state.logs) : null; }
function populateChannelSelect() { const select = $('#channelSelect'); select.innerHTML = state.channels.map(c => `<option value="${c.id}">${c.name || `渠道 ${c.id}`} (#${c.id}, ${Number(c.status) ? '启用' : '停用'})</option>`).join(''); if (state.selectedId != null) select.value = state.selectedId; }
function metric(label, value, foot, tone = '') { return `<div class="metric-card panel ${tone}"><span class="metric-label">${label}</span><strong class="metric-value">${value}</strong><span class="metric-foot">${foot}</span></div>`; }
function renderMetrics(a) { if (!a) { $('#metricGrid').innerHTML = ''; return; } $('#metricGrid').innerHTML = [metric('成功率', pct(a.success), `错误率 ${pct(a.errors / Math.max(a.requests, 1))}`, a.success >= .9 ? 'good' : 'warn'), metric('平均响应时间', `${fmt(a.avgTime)}<small> ms</small>`, `P95 ${fmt(a.p95)} ms`, a.avgTime < 900 ? 'good' : 'warn'), metric('额度消耗', fmt(a.quota), `均次 ${fmt(a.perRequest, 1)}`, a.perRequest < 180 ? 'good' : 'warn'), metric('请求量', fmt(a.requests), `近 ${state.days} 天趋势 ${a.trend >= 0 ? '+' : ''}${pct(a.trend)}`, ''), metric('模型数', fmt(Object.keys(a.modelMap).length), `集中度 ${pct(Math.max(...Object.values(a.modelMap), 0) / Math.max(a.requests, 1))}`, ''), metric('综合得分', `${a.score}<small>/100</small>`, `建议：${a.verdict}`, a.tone)].join(''); }
function svgAxes(W, H, pad, labels) { return `<g stroke="#e7edf4" stroke-width="1">${[0,.25,.5,.75,1].map(v => `<line x1="${pad.l}" x2="${W - pad.r}" y1="${pad.t + (H - pad.t - pad.b) * v}" y2="${pad.t + (H - pad.t - pad.b) * v}"/>`).join('')}</g>${labels.map((k, i) => `<text x="${pad.l + (i / Math.max(labels.length - 1, 1)) * (W - pad.l - pad.r)}" y="${H - 7}" text-anchor="middle" font-size="10" fill="#8a98ab">${k.slice(5)}</text>`).join('')}`; }
function renderTrend(a) { const keys = Object.keys(a.daily).sort().slice(-Math.max(3, state.days)); const W = 900, H = 268, pad = { l: 35, r: 15, t: 15, b: 28 }, iw = W - pad.l - pad.r, ih = H - pad.t - pad.b, max = Math.max(...keys.map(k => a.daily[k].requests), 1), x = i => pad.l + i / Math.max(keys.length - 1, 1) * iw; const bars = keys.map((k, i) => { const bw = Math.min(26, iw / keys.length * .46), bx = x(i) - bw / 2, ok = a.daily[k].requests - a.daily[k].errors, er = a.daily[k].errors, hs = ok / max * ih, he = er / max * ih; return `<rect x="${bx}" y="${pad.t + ih - hs}" width="${bw}" height="${hs}" rx="4" fill="#24a273"/><rect x="${bx}" y="${pad.t + ih - hs - he}" width="${bw}" height="${he}" rx="4" fill="#e05b5b"/><text x="${x(i)}" y="${pad.t + ih - hs - he - 6}" text-anchor="middle" font-size="10" fill="#5c6e84">${ok + er}</text>`; }).join(''); $('#trendChart').innerHTML = `<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${svgAxes(W, H, pad, keys)}${bars}</svg>`; }
function renderResponse(a) { const keys = Object.keys(a.daily).sort().slice(-Math.max(3, state.days)); const W = 900, H = 268, pad = { l: 42, r: 15, t: 15, b: 28 }, iw = W - pad.l - pad.r, ih = H - pad.t - pad.b; const values = keys.map(k => a.daily[k].times.filter(Boolean).reduce((s, v) => s + v, 0) / Math.max(1, a.daily[k].times.filter(Boolean).length)); const max = Math.max(...values, a.p95, 1), x = i => pad.l + i / Math.max(keys.length - 1, 1) * iw, y = v => pad.t + ih - v / max * ih; const points = values.map((v, i) => `${x(i)},${y(v)}`).join(' '); $('#responseChart').innerHTML = `<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${svgAxes(W, H, pad, keys)}<polyline points="${points}" fill="none" stroke="#2f6dde" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${values.map((v, i) => `<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="#2f6dde"/><text x="${x(i)}" y="${y(v) - 9}" text-anchor="middle" font-size="10" fill="#60748d">${fmt(v)}ms</text>`).join('')}</svg>`; }
function renderConclusion(a) { if (!a) { $('#conclusion').textContent = '请选择渠道并开始分析'; return; } const copy = a.verdict === '建议续费' ? '该渠道在稳定性、成本和模型覆盖上表现均衡，建议继续复充，并保留异常监控。' : a.verdict === '谨慎续费' ? '该渠道具备使用价值，但仍有成本或稳定性短板，建议小额续费并设置观察阈值。' : a.verdict === '暂不续费' ? '当前表现不足以支持继续投入，建议先观察修复结果，再决定是否恢复额度。' : '渠道的稳定性或成本效率明显偏弱，建议迁移流量并寻找替代渠道。'; $('#conclusion').innerHTML = `<div class="conclusion-title ${a.tone}">${a.verdict}</div><div class="conclusion-tags"><span>总分 ${a.score}</span><span>成功率 ${pct(a.success)}</span><span>异常率 ${pct(a.errors / Math.max(a.requests, 1))}</span></div><p>${copy}</p>`; }
function renderModels(a) { const entries = Object.entries(a.modelMap).sort((x, y) => y[1] - x[1]).slice(0, 5), max = Math.max(...entries.map(x => x[1]), 1); $('#modelChart').innerHTML = entries.map(([name, count]) => `<div class="model-row"><span class="model-name">${name}</span><div class="model-track"><div class="model-fill" style="width:${count / max * 100}%"></div></div><span class="model-count">${count}</span></div>`).join('') || '<p>暂无模型数据</p>'; }
function renderAnomalies(a) { $('#anomalyCount').textContent = a?.anomaly.length || 0; $('#anomalyTable').innerHTML = a?.anomaly.map(l => `<tr><td>${new Date(Number(l.created_at) * 1000).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })}</td><td>${l.model_name || '-'}</td><td>${l.request_id || '-'}</td><td>${fmt(l.use_time)}ms</td><td>${fmt(l.quota)}</td><td><span class="severity ${isError(l) ? 'high' : 'medium'}">${isError(l) ? '错误/限流' : '慢请求'}</span></td><td>${String(l.content || '').slice(0, 22)}</td></tr>`).join('') || '<tr><td colspan="7">当前窗口内暂无明显异常</td></tr>'; }
function renderScore(a) { const score = a?.score || 0; $('#scoreValue').textContent = score; $('#scoreVerdict').textContent = a?.verdict || '等待分析'; $('#scoreCaption').textContent = a ? `${a.channel.name} · 接口基线 ${fmt(a.channel.response_time || 0)} ms · ${fmt(a.requests)} 条有效请求` : '请选择渠道并开始分析'; $('#scoreRing').style.background = `conic-gradient(${a?.tone === 'good' ? '#199c70' : a?.tone === 'bad' ? '#d95454' : '#d4830c'} ${score * 3.6}deg,#d8e2ef ${score * 3.6}deg)`; }
function renderReport(a) { $('#reportPreview').innerHTML = a ? `<strong>${$('#reportDate').value || yesterday} 日报</strong><br>${a.channel.name} · 评分 ${a.score} · ${a.verdict}<br>请求 ${fmt(a.requests)} 次，成功率 ${pct(a.success)}，平均响应 ${fmt(a.avgTime)} ms，额度消耗 ${fmt(a.quota)}，异常 ${a.anomaly.length} 条。` : '暂无数据'; }
function renderAll() { const a = selectedAnalysis(); renderMetrics(a); renderScore(a); renderConclusion(a); if (a) { renderTrend(a); renderResponse(a); renderModels(a); renderAnomalies(a); renderReport(a); $('#trendPeriod').textContent = `最近 ${state.days} 天`; } }
async function apiFetch(url, headers) { const productionProxy = !['localhost', '127.0.0.1'].includes(location.hostname) && location.protocol.startsWith('http'); if (productionProxy) { const response = await fetch('/proxy', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url, headers }) }); if (response.status === 404) return fetch(url, { headers, credentials: 'include' }); return response; } return fetch(url, { headers, credentials: 'include' }); }
async function fetchPages(url, headers, maxPages = 20) { const result = []; for (let page = 1; page <= maxPages; page++) { const pageUrl = new URL(url); pageUrl.searchParams.set('p', page); pageUrl.searchParams.set('page_size', '100'); const response = await apiFetch(pageUrl.toString(), headers); if (!response.ok) throw new Error(`接口返回 ${response.status}`); const json = await response.json(); const items = json?.data?.items || []; result.push(...items); const total = Number(json?.data?.total || 0); if (!items.length || (total && result.length >= total) || items.length < 100) break; } return result; }
async function loadRealData() { const base = ($('#baseUrl')?.value || 'https://maolaoapi.com').replace(/\/$/, ''); const headers = { 'Content-Type': 'application/json' }; const token = ($('#authorization')?.value || '').trim(); if (token) headers.Authorization = /^Bearer\s+/i.test(token) ? token : `Bearer ${token}`; if ($('#userId')?.value) headers['New-Api-User'] = $('#userId').value.trim(); if (!headers.Authorization) throw new Error('请填写 Authorization Bearer Token'); const startDate = $('#startDate').value ? new Date(`${$('#startDate').value}T00:00:00`).getTime() / 1000 : Math.floor(Date.now() / 1000) - 7 * 86400; const endDate = $('#endDate').value ? new Date(`${$('#endDate').value}T23:59:59`).getTime() / 1000 : Math.floor(Date.now() / 1000); state.days = Math.max(1, Math.ceil((endDate - startDate) / 86400)); const channels = await fetchPages(`${base}/api/channel/`, headers); const all = []; for (const c of channels) { try { const u = new URL(`${base}/api/log/`); u.searchParams.set('channel', c.id); u.searchParams.set('start_timestamp', startDate); u.searchParams.set('end_timestamp', endDate); if ($('#analysisPath').value === 'consumption-error') u.searchParams.set('type', '2'); all.push(...await fetchPages(u.toString(), headers)); } catch (e) {} } setData({ channels, logs: all }, false); toast(`已拉取 ${channels.length} 个渠道、${all.length} 条日志`); }
function parseInputs() { const channels = unwrapItems(JSON.parse($('#channelJson').value || '[]')), logs = unwrapItems(JSON.parse($('#logJson').value || '[]')); if (!channels.length) throw new Error('渠道 JSON 中没有 data.items'); setData({ channels, logs }, false); toast(`已解析 ${channels.length} 个渠道、${logs.length} 条日志`); }
function fillDemo() { const data = demoData(); $('#channelJson').value = JSON.stringify({ success: true, data: { items: data.channels } }, null, 2); $('#logJson').value = JSON.stringify({ success: true, data: { page: 1, page_size: 100, total: data.logs.length, items: data.logs } }, null, 2); setData(data, true); }
function reportText() { const a = selectedAnalysis(); if (!a) return ''; return `${$('#reportDate').value || yesterday} 渠道日报\n渠道：${a.channel.name}（ID ${a.channel.id}）\n结论：${a.verdict}｜综合评分 ${a.score}/100\n请求量：${a.requests}\n成功率：${pct(a.success)}\n错误率：${pct(a.errors / Math.max(a.requests, 1))}\n平均响应：${fmt(a.avgTime)}ms（P95 ${fmt(a.p95)}ms）\n额度消耗：${fmt(a.quota)} quota，均次 ${fmt(a.perRequest, 1)}\n模型覆盖：${Object.keys(a.modelMap).join('、')}\n异常请求：${a.anomaly.length} 条`; }
function toast(msg) { const el = $('#toast'); el.textContent = msg; el.classList.add('show'); clearTimeout(window.__toast); window.__toast = setTimeout(() => el.classList.remove('show'), 2600); }
$('#fillDemo').addEventListener('click', fillDemo); $('#startAnalysis').addEventListener('click', () => { try { parseInputs(); } catch (e) { toast(`解析失败：${e.message}`); } }); $('#clearData').addEventListener('click', () => { $('#channelJson').value = ''; $('#logJson').value = ''; setData({ channels: [], logs: [] }, false); $('#dataStatus').textContent = '已清空数据'; }); $('#channelSelect').addEventListener('change', e => { state.selectedId = e.target.value; renderAll(); }); $('#analysisPath').addEventListener('change', renderAll); $('#reportDate').addEventListener('change', () => renderReport(selectedAnalysis()));
$('#loadData').addEventListener('click', async () => { const button = $('#loadData'); try { button.disabled = true; button.textContent = '拉取中…'; await loadRealData(); } catch (e) { toast(`拉取失败：${e.message || '请检查地址和认证'}`); } finally { button.disabled = false; button.textContent = '拉取真实数据'; } });
for (const [inputId, targetId] of [['channelFile', 'channelJson'], ['logFile', 'logJson']]) $(`#${inputId}`).addEventListener('change', async e => { const file = e.target.files[0]; if (file) $(`#${targetId}`).value = await file.text(); });
$('#copyReport').addEventListener('click', async () => { await navigator.clipboard.writeText(reportText()); toast('日报已复制'); }); $('#downloadReport').addEventListener('click', () => { const blob = new Blob([reportText()], { type: 'text/plain;charset=utf-8' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `channel-report-${$('#reportDate').value || 'daily'}.txt`; a.click(); URL.revokeObjectURL(a.href); toast('日报已下载'); }); $('#dailyToggle').addEventListener('change', async e => { localStorage.setItem('dailyReminder', e.target.checked ? '1' : '0'); if (e.target.checked && 'Notification' in window && Notification.permission === 'default') await Notification.requestPermission(); toast(e.target.checked ? '日报提醒已启用' : '日报提醒已关闭'); }); if (localStorage.getItem('dailyReminder') === '1') $('#dailyToggle').checked = true;
fillDemo();
